import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "Privacy policy for the Integrity1 Home Inspections website. Learn how we collect, use, and protect your personal information.",
  openGraph: {
    title: "Privacy Policy",
    description:
      "Privacy policy for the Integrity1 Home Inspections website. Learn how we collect, use, and protect your personal information.",
    url: "https://integrity1-home-inspections.vercel.app/privacy-policy",
  },
};

export default function PrivacyPolicyPage() {
  return (
    <section
      style={{
        backgroundColor: "white",
        padding: "54px 0 80px",
      }}
    >
      <div
        className="mx-auto"
        style={{ maxWidth: 1080, padding: "0 20px" }}
      >
        <h1
          style={{
            fontSize: 30,
            fontWeight: 500,
            color: "rgb(51, 51, 51)",
            marginBottom: 20,
          }}
        >
          Privacy Policy
        </h1>

        <P>Last updated: June 24, 2021</P>

        <P>
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </P>

        <P>
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy. This Privacy Policy has been
          created with the help of the Privacy Policy Generator.
        </P>

        <H1>Interpretation and Definitions</H1>
        <H2>Interpretation</H2>
        <P>
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions shall
          have the same meaning regardless of whether they appear in singular or
          in plural.
        </P>

        <H2>Definitions</H2>
        <P>For the purposes of this Privacy Policy:</P>
        <ul style={{ paddingLeft: 20, marginBottom: 16 }}>
          <Li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</Li>
          <Li><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Integrity 1 Home Inspections.</Li>
          <Li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</Li>
          <Li><strong>Country</strong> refers to: Florida, United States</Li>
          <Li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</Li>
          <Li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</Li>
          <Li><strong>Service</strong> refers to the Website.</Li>
          <Li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</Li>
          <Li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</Li>
          <Li><strong>Website</strong> refers to Integrity 1 Home Inspections, accessible from https://integrity1homeinspections.com/</Li>
          <Li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</Li>
        </ul>

        <H1>Collecting and Using Your Personal Data</H1>
        <H2>Types of Data Collected</H2>
        <H3>Personal Data</H3>
        <P>
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You. Personally identifiable information may include, but is
          not limited to:
        </P>
        <ul style={{ paddingLeft: 20, marginBottom: 16 }}>
          <Li>Email address</Li>
          <Li>First name and last name</Li>
          <Li>Phone number</Li>
          <Li>Address, State, Province, ZIP/Postal code, City</Li>
          <Li>Usage Data</Li>
        </ul>

        <H3>Usage Data</H3>
        <P>
          Usage Data is collected automatically when using the Service. Usage
          Data may include information such as Your Device&apos;s Internet
          Protocol address (e.g. IP address), browser type, browser version, the
          pages of our Service that You visit, the time and date of Your visit,
          the time spent on those pages, unique device identifiers and other
          diagnostic data.
        </P>

        <H3>Tracking Technologies and Cookies</H3>
        <P>
          We use Cookies and similar tracking technologies to track the activity
          on Our Service and store certain information. Cookies can be
          &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent
          Cookies remain on Your personal computer or mobile device when You go
          offline, while Session Cookies are deleted as soon as You close Your
          web browser.
        </P>

        <H2>Use of Your Personal Data</H2>
        <P>The Company may use Personal Data for the following purposes:</P>
        <ul style={{ paddingLeft: 20, marginBottom: 16 }}>
          <Li>To provide and maintain our Service, including to monitor the usage of our Service.</Li>
          <Li>To manage Your Account: to manage Your registration as a user of the Service.</Li>
          <Li>To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</Li>
          <Li>To provide You with news, special offers and general information about other goods, services and events which we offer.</Li>
          <Li>To manage Your requests: To attend and manage Your requests to Us.</Li>
        </ul>

        <H2>Retention of Your Personal Data</H2>
        <P>
          The Company will retain Your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy. We will
          retain and use Your Personal Data to the extent necessary to comply
          with our legal obligations, resolve disputes, and enforce our legal
          agreements and policies.
        </P>

        <H2>Security of Your Personal Data</H2>
        <P>
          The security of Your Personal Data is important to Us, but remember
          that no method of transmission over the Internet, or method of
          electronic storage is 100% secure. While We strive to use commercially
          acceptable means to protect Your Personal Data, We cannot guarantee its
          absolute security.
        </P>

        <H1>Children&apos;s Privacy</H1>
        <P>
          Our Service does not address anyone under the age of 13. We do not
          knowingly collect personally identifiable information from anyone under
          the age of 13. If You are a parent or guardian and You are aware that
          Your child has provided Us with Personal Data, please contact Us.
        </P>

        <H1>Changes to this Privacy Policy</H1>
        <P>
          We may update Our Privacy Policy from time to time. We will notify You
          of any changes by posting the new Privacy Policy on this page. You are
          advised to review this Privacy Policy periodically for any changes.
        </P>

        <H1>Contact Us</H1>
        <P>
          If you have any questions about this Privacy Policy, You can contact us:
        </P>
        <ul style={{ paddingLeft: 20, marginBottom: 16 }}>
          <Li>By phone number: 561.565.8513</Li>
          <Li>By email: integrity1homeinspections@gmail.com</Li>
        </ul>
      </div>
    </section>
  );
}

function H1({ children }: { children: React.ReactNode }) {
  return (
    <h2 style={{ fontSize: 30, fontWeight: 500, color: "rgb(51, 51, 51)", marginTop: 32, marginBottom: 16 }}>
      {children}
    </h2>
  );
}

function H2({ children }: { children: React.ReactNode }) {
  return (
    <h3 style={{ fontSize: 26, fontWeight: 500, color: "rgb(51, 51, 51)", marginTop: 24, marginBottom: 12 }}>
      {children}
    </h3>
  );
}

function H3({ children }: { children: React.ReactNode }) {
  return (
    <h4 style={{ fontSize: 22, fontWeight: 500, color: "rgb(51, 51, 51)", marginTop: 20, marginBottom: 10 }}>
      {children}
    </h4>
  );
}

function P({ children }: { children: React.ReactNode }) {
  return (
    <p style={{ fontSize: 16, lineHeight: "27px", color: "rgb(29, 41, 67)", marginBottom: 16 }}>
      {children}
    </p>
  );
}

function Li({ children }: { children: React.ReactNode }) {
  return (
    <li style={{ fontSize: 16, lineHeight: "26px", color: "rgb(29, 41, 67)", marginBottom: 4 }}>
      {children}
    </li>
  );
}
